services:
  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - visa_types
  app:
    build: .
    env_file:
      - .env
    ports:
      - 80:80
    networks:
      - visa_types

networks:
  visa_types:
